<?php

declare(strict_types=1);

namespace Evolver;

/**
 * Skill Publisher - Converts Genes to SKILL.md format and publishes to Hub.
 *
 * Ported from evolver/src/gep/skillPublisher.js
 */
final class SkillPublisher
{
    private const REQUEST_TIMEOUT = 15;
    private const MIN_NAME_LENGTH = 6;

    private GepA2AProtocol $protocol;
    private string $hubUrl;

    public function __construct(?GepA2AProtocol $protocol = null, ?string $hubUrl = null)
    {
        $this->protocol = $protocol ?? new GepA2AProtocol();
        // If hubUrl is explicitly passed (even empty string), use it
        // Otherwise check env vars, with no default (empty string means "no hub")
        if ($hubUrl !== null) {
            $this->hubUrl = $this->normalizeUrl($hubUrl);
        } else {
            $envUrl = getenv('A2A_HUB_URL') ?: getenv('EVOMAP_HUB_URL') ?: '';
            $this->hubUrl = $this->normalizeUrl($envUrl);
        }
    }

    /**
     * Convert a Gene object into SKILL.md format (Claude/Anthropic style).
     *
     * @param array $gene Gene asset
     */
    public function geneToSkillMd(array $gene): string
    {
        $rawName = $gene['id'] ?? 'unnamed-skill';
        $name = $this->sanitizeSkillName($rawName);

        if ($name === null) {
            $name = $this->generateFallbackName($gene);
        }

        $desc = preg_replace('/[\r\n]+/', ' ', trim($gene['summary'] ?? 'AI agent skill distilled from evolution experience.'));

        $lines = [
            '---',
            "name: {$name}",
            "description: {$desc}",
            '---',
            '',
            "# {$name}",
            '',
        ];

        // Trigger Signals
        $signalsMatch = $gene['signals_match'] ?? [];
        if (!empty($signalsMatch)) {
            $lines[] = '## Trigger Signals';
            $lines[] = '';
            foreach ($signalsMatch as $s) {
                $lines[] = "- `{$s}`";
            }
            $lines[] = '';
        }

        // Preconditions
        $preconditions = $gene['preconditions'] ?? [];
        if (!empty($preconditions)) {
            $lines[] = '## Preconditions';
            $lines[] = '';
            foreach ($preconditions as $p) {
                $lines[] = "- {$p}";
            }
            $lines[] = '';
        }

        // Strategy
        $strategy = $gene['strategy'] ?? [];
        if (!empty($strategy)) {
            $lines[] = '## Strategy';
            $lines[] = '';
            foreach ($strategy as $i => $step) {
                $lines[] = ($i + 1) . ". {$step}";
            }
            $lines[] = '';
        }

        // Constraints
        $constraints = $gene['constraints'] ?? [];
        if (!empty($constraints)) {
            $lines[] = '## Constraints';
            $lines[] = '';
            if (isset($constraints['max_files'])) {
                $lines[] = "- Max files: {$constraints['max_files']}";
            }
            if (!empty($constraints['forbidden_paths'])) {
                $forbidden = implode(', ', $constraints['forbidden_paths']);
                $lines[] = "- Forbidden paths: {$forbidden}";
            }
            $lines[] = '';
        }

        // Validation
        $validation = $gene['validation'] ?? [];
        if (!empty($validation)) {
            $lines[] = '## Validation';
            $lines[] = '';
            foreach ($validation as $cmd) {
                $lines[] = '```bash';
                $lines[] = $cmd;
                $lines[] = '```';
                $lines[] = '';
            }
        }

        $lines[] = '---';
        $lines[] = '';
        $lines[] = '*This Skill was generated by [Evolver](https://github.com/autogame-17/evolver) and is distributed under the [EvoMap Skill License (ESL-1.0)](https://evomap.ai/terms). Unauthorized redistribution, bulk scraping, or republishing is prohibited. See LICENSE file for full terms.*';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Publish a Gene as a Skill to the Hub skill store.
     *
     * @param array $gene Gene asset
     * @param array $opts { category?: string, tags?: string[] }
     * @return array{ok: bool, result?: array, error?: string, status?: int}
     */
    public function publishToHub(array $gene, array $opts = []): array
    {
        if (empty($this->hubUrl)) {
            return ['ok' => false, 'error' => 'no_hub_url'];
        }

        $content = $this->geneToSkillMd($gene);
        $nodeId = $this->protocol->getNodeId();

        // Extract name from frontmatter
        $fmName = null;
        if (preg_match('/^name:\s*(.+)$/m', $content, $matches)) {
            $fmName = trim($matches[1]);
        }

        $derivedName = $fmName
            ? strtolower(preg_replace('/[^a-z0-9]+/', '_', $fmName))
            : preg_replace('/^gene_/', '', $gene['id'] ?? 'unnamed');

        $skillId = 'skill_' . $derivedName;

        $body = [
            'sender_id' => $nodeId,
            'skill_id' => $skillId,
            'content' => $content,
            'category' => $opts['category'] ?? $gene['category'] ?? null,
            'tags' => $opts['tags'] ?? $gene['signals_match'] ?? [],
        ];

        $endpoint = $this->hubUrl . '/a2a/skill/store/publish';

        try {
            $response = $this->httpPost($endpoint, $body);

            if ($response['status'] === 201 || $response['status'] === 200) {
                return ['ok' => true, 'result' => $response['body']];
            }

            if ($response['status'] === 409) {
                // Skill already exists, try update
                return $this->updateOnHub($nodeId, $skillId, $content, $opts, $gene);
            }

            return [
                'ok' => false,
                'error' => $response['body']['error'] ?? 'publish_failed',
                'status' => $response['status'],
            ];
        } catch (\Throwable $e) {
            return ['ok' => false, 'error' => $e->getMessage()];
        }
    }

    /**
     * Update an existing Skill on the Hub (new version).
     *
     * @param string $nodeId
     * @param string $skillId
     * @param string $content
     * @param array $opts
     * @param array $gene
     * @return array{ok: bool, result?: array, error?: string, status?: int}
     */
    public function updateOnHub(string $nodeId, string $skillId, string $content, array $opts, array $gene): array
    {
        if (empty($this->hubUrl)) {
            return ['ok' => false, 'error' => 'no_hub_url'];
        }

        $body = [
            'sender_id' => $nodeId,
            'skill_id' => $skillId,
            'content' => $content,
            'category' => $opts['category'] ?? $gene['category'] ?? null,
            'tags' => $opts['tags'] ?? $gene['signals_match'] ?? [],
            'changelog' => 'Iterative evolution update',
        ];

        $endpoint = $this->hubUrl . '/a2a/skill/store/update';

        try {
            $response = $this->httpPut($endpoint, $body);

            if ($response['status'] >= 200 && $response['status'] < 300) {
                return ['ok' => true, 'result' => $response['body']];
            }

            return [
                'ok' => false,
                'error' => $response['body']['error'] ?? 'update_failed',
                'status' => $response['status'],
            ];
        } catch (\Throwable $e) {
            return ['ok' => false, 'error' => $e->getMessage()];
        }
    }

    /**
     * Sanitize skill name from raw gene ID.
     */
    private function sanitizeSkillName(string $rawName): ?string
    {
        $name = preg_replace('/[\r\n]+/', '-', $rawName);
        $name = preg_replace('/^gene_distilled_/', '', $name);
        $name = preg_replace('/^gene_/', '', $name);
        $name = str_replace('_', '-', $name);

        // Skip names that are just timestamps or IDE/editor names
        if (preg_match('/^\d{8,}/', $name) || preg_match('/^(cursor|vscode|vim|emacs|windsurf|copilot|cline|codex)[-]?\d*$/i', $name)) {
            return null;
        }

        // Remove trailing long numbers (timestamps)
        $name = preg_replace('/-?\d{10,}$/', '', $name);
        $name = preg_replace('/-+$/', '', $name);

        // Check minimum length (excluding dashes)
        if (strlen(str_replace('-', '', $name)) < self::MIN_NAME_LENGTH) {
            return null;
        }

        return $name;
    }

    /**
     * Generate fallback skill name from gene signals/summary.
     */
    private function generateFallbackName(array $gene): string
    {
        $fallbackWords = [];

        // Extract words from signals_match
        $signalsMatch = $gene['signals_match'] ?? [];
        if (is_array($signalsMatch)) {
            foreach (array_slice($signalsMatch, 0, 3) as $s) {
                $words = preg_split('/[^a-z0-9]+/i', strtolower((string)$s));
                foreach ($words as $w) {
                    if (strlen($w) >= 3 && count($fallbackWords) < 5) {
                        $fallbackWords[] = $w;
                    }
                }
            }
        }

        // If not enough words, extract from summary
        if (count($fallbackWords) < 2 && !empty($gene['summary'])) {
            $words = preg_split('/[^a-z0-9]+/i', strtolower((string)$gene['summary']));
            foreach ($words as $w) {
                if (strlen($w) >= 3 && count($fallbackWords) < 5) {
                    $fallbackWords[] = $w;
                }
            }
        }

        // Deduplicate
        $fallbackWords = array_values(array_unique($fallbackWords));

        return count($fallbackWords) >= 2
            ? implode('-', $fallbackWords)
            : 'auto-distilled-skill';
    }

    /**
     * Perform HTTP POST request.
     */
    private function httpPost(string $url, array $data): array
    {
        return $this->httpRequest($url, $data, 'POST');
    }

    /**
     * Perform HTTP PUT request.
     */
    private function httpPut(string $url, array $data): array
    {
        return $this->httpRequest($url, $data, 'PUT');
    }

    /**
     * Perform HTTP request.
     */
    private function httpRequest(string $url, array $data, string $method): array
    {
        $ch = curl_init($url);
        if ($ch === false) {
            throw new \RuntimeException("Failed to initialize curl");
        }

        $payload = json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        curl_setopt_array($ch, [
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_POSTFIELDS => $payload,
            CURLOPT_HTTPHEADER => array_merge(
                ['Content-Type: application/json'],
                $this->buildAuthHeaders()
            ),
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => self::REQUEST_TIMEOUT,
            CURLOPT_CONNECTTIMEOUT => 5,
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        // curl_close() is deprecated in PHP 8.5 and has no effect since PHP 8.0
        // The handle will be cleaned up automatically when $ch goes out of scope

        if ($error) {
            throw new \RuntimeException("HTTP error: " . $error);
        }

        $body = [];
        if (!empty($response)) {
            $decoded = json_decode($response, true);
            if (is_array($decoded)) {
                $body = $decoded;
            }
        }

        return ['status' => (int)$httpCode, 'body' => $body];
    }

    /**
     * Build authentication headers for Hub requests.
     */
    private function buildAuthHeaders(): array
    {
        $headers = [];
        $authToken = getenv('EVOMAP_AUTH_TOKEN') ?: getenv('A2A_AUTH_TOKEN');
        if ($authToken) {
            $headers[] = 'Authorization: Bearer ' . $authToken;
        }
        return $headers;
    }

    private function normalizeUrl(string $url): string
    {
        return rtrim($url, '/');
    }

    public function getHubUrl(): string
    {
        return $this->hubUrl;
    }
}
